#!/bin/csh
#
# Last Change: 07-Feb-2002.
# Written By:  Muraoka Taro <koron@tka.att.ne.jp>

if ($1 == '') then
  echo ""
  echo "Please specify package version string."
  echo "Example: './mkpkg 1.0-xxx '"
  exit
endif

set pkgdir = "chalice-$1"
cd ..
rm -rf $pkgdir
cvs export -D now -d $pkgdir proj/chalice
rm -rf $pkgdir/tools # dolibÇÕégÇ¡ÇƒÇ»Ç¢ÇÃÇ≈è¡ãé
qkc -s -u ${pkgdir}/*/*.vim ${pkgdir}/install.sh ${pkgdir}/mkpkg

tar cyvf "${pkgdir}.tar.bz2" $pkgdir
